// platform
export const GET_DEVICES = 'GET_DEVICES';
export const GET_DEVICE = 'GET_DEVICE';
export const GET_REALTIME_UPDATES = 'GET_REALTIME_UPDATES';
export const STOP_REALTIME_UPDATES = 'STOP_REALTIME_UPDATES';

// menu
export const OPEN_MAIN_MENU = 'OPEN_MAIN_MENU';
export const CLOSE_MAIN_MENU = 'CLOSE_MAIN_MENU';
